apiVersion: v1
kind: Secret
metadata:
  name: "knag-users-db-secret"
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "knag-users-db-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $var to existing secret data or generate a random one when not exists
  {{- $rsKey := (get $secretData "username") | default (randAlphaNum 32 | b64enc) }}
  {{- $password := (get $secretData "mongodb-passwords") | default (randAlphaNum 32 | b64enc) }}
  {{- $rootPassword := (get $secretData "mongodb-root-password") | default (randAlphaNum 32 | b64enc) }}
  mongodb-replica-set-key: {{ $rsKey | quote }}
  mongodb-passwords: {{ $password | quote }}
  mongodb-root-password: {{ $rootPassword | quote }}

