apiVersion: v1
kind: Namespace
metadata:
  name: knag
  labels:
    # inject Kuma sidecar into every Pod in that Namespace,
    # unless a user explicitly opts out on per-Pod basis
    kuma.io/sidecar-injection: enabled
  annotations:
    kuma.io/mesh: knag-mesh

---

apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: knag-mesh
spec:
  mtls:
    enabledBackend: ca-1
    backends:
      - name: ca-1
        type: builtin
        dpCert:
          rotation:
            expiration: 1d
        conf:
          caCert:
            RSAbits: 2048
            expiration: 10y

---

apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: knag-mesh
metadata: 
  name: route-all-knag-mesh
spec: 
  sources: 
    - match: 
        kuma.io/service: '*'
  destinations: 
    - match: 
        kuma.io/service: '*'
  conf: 
    loadBalancer: 
      roundRobin: 
    destination: 
      kuma.io/service: '*'

---

apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: knag-mesh
metadata: 
  name: allow-all-knag-mesh
spec: 
  sources: 
    - match: 
        kuma.io/service: '*'
  destinations: 
    - match: 
        kuma.io/service: '*'

---

apiVersion: kuma.io/v1alpha1
kind: CircuitBreaker
mesh: knag-mesh
metadata: 
  name: circuit-breaker-all-knag-mesh
spec: 
  sources: 
    - match: 
        kuma.io/service: '*'
  destinations: 
    - match: 
        kuma.io/service: '*'
  conf: 
    thresholds: 
      maxConnections: 1024
      maxPendingRequests: 1024
      maxRetries: 3
      maxRequests: 1024

---

apiVersion: kuma.io/v1alpha1
kind: Retry
mesh: knag-mesh
metadata: 
  name: retry-all-knag-mesh
spec: 
  sources: 
    - match: 
        kuma.io/service: '*'
  destinations: 
    - match: 
        kuma.io/service: '*'
  conf: 
    http: 
      numRetries: 5
      perTryTimeout: 16s
      backOff: 
        baseInterval: 0.025s
        maxInterval: 0.250s
    tcp: 
      maxConnectAttempts: 5
    grpc: 
      numRetries: 5
      perTryTimeout: 16s
      backOff: 
        baseInterval: 0.025s
        maxInterval: 0.250s

---

apiVersion: kuma.io/v1alpha1
kind: Timeout
mesh: knag-mesh
metadata: 
  name: timeout-all-knag-mesh
spec: 
  sources: 
    - match: 
        kuma.io/service: '*'
  destinations: 
    - match: 
        kuma.io/service: '*'
  conf: 
    connectTimeout: 5s
    tcp: 
      idleTimeout: 3600s
    http: 
      requestTimeout: 15s
      idleTimeout: 3600s
    grpc: 
      streamIdleTimeout: 300s
