
kong:
  image:
    repository: kong
    tag: "2.8"

  ingressController:
    enabled: true
    installCRDs: false

  admin:
    enabled: true
    http:
      enabled: true
      servicePort: 8001
      containerPort: 8001

users:
  enabled: true
